# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main",  "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/out
          key: out
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -a
          pwd
      - name: Run dotnet restore & publish
        id: build
        run: |
          cd src/Kafka
          dotnet restore
          dotnet publish -c Release -o ~/out
          cp Dockerfile ~/out
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.CHANGELOG_RELEASE }}
          output-file: "false"
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changlog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.clean_changelog }}
      outputs:
        version: ${{ steps.changelog.outputs.tag }}        
  build-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v2
        with:
            path: ~/out
            key: out
      - name: Run Docker build
        run: |
           pwd
           ls -a ~/out
           cat ~/out/Dockerfile
